### ISSUE TITLE
Can't start the webapp

### ISSUE THREAD

**Issue by ShulinChen** [maddevsio/openfreecab-storage#1] opened 2017-02-21 09:14 UTC
Hi first of all, thanks for sharing this project, it's awesome!
The only two changes I made is to comment out 'github.com/labstack/echo/engine/standard' in the http.go and change line 49 to 'h.e.Start(h.os.Config().HTTPBindAddr)' as the echo library has changed.
But for some reason, after I run './openfreecab-storage,' it gives me the following error.

<img width="1273" alt="screenshot" src="https://cloud.githubusercontent.com/assets/8204913/23158143/e5d63e2a-f7d2-11e6-8f9f-762663af492f.png">

And here is what my terminal looks like:
<img width="586" alt="screenshot" src="https://cloud.githubusercontent.com/assets/8204913/23158209/285517ee-f7d3-11e6-9aca-5f92dc705f9c.png">

**Comment by gen1us2k** [comment] 2017-02-21 13:07
Hey.  The project consist from multiple components.
1. Storage
2. Crawler
3. Web/mobile clients to display infrormation.

You can find full information how to install it here. 
https://github.com/maddevsio/openfreecabs

**Comment by gen1us2k** [comment] 2017-02-21 13:09
By design storage only stores data and returns nearest drivers. That's all. To display it there are mobile apps or web app https://github.com/maddevsio/openfreecabs-android
https://github.com/maddevsio/openfreecabs-ios
https://github.com/maddevsio/openfreecabs-web

**Comment by lkkadiri** [comment] 2017-02-22 04:03
@gen1us2k The package "github.com/labstack/echo/engine/standard" is not available as it has been changed. So this issue is still relevant.

**Comment by gen1us2k** [comment] 2017-02-22 04:24
Oh. I see. I'll fix it in #2

**Comment by ShulinChen** [comment] 2017-02-22 07:01
@gen1us2k Thanks, that solves my issue. 
Just as a friendly suggestion, I find this repo by reading this article (https://blog.maddevs.io/how-we-built-a-backend-system-for-uber-like-map-with-animated-cars-on-it-using-go-29d5dcd517a#.dxjedgjhw)
You might wanna update the link at the end of the article to be 'https://github.com/maddevsio/openfreecab' since this article must have been read a lot as it got to the front page of hacker news yesterday.

**Comment by gen1us2k** [comment] 2017-02-22 07:03
Yes. It can me a misleading. I'll update it. Thanks

**Comment by gen1us2k** [comment] 2017-02-22 15:03
Updated link at blog post. Fixed #2. Closing the issue

**Closed as completed by gen1us2k** 2017-02-22 15:03 UTC
